name: build image

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: Check if Git tag exists
        run: echo "::set-env name=HEAD_TAG::$(git tag --points-at HEAD)"
      - name: Check if Git tag exists
        run: echo $HEAD_TAG
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
        if: env.HEAD_TAG != '' 
      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        if: env.HEAD_TAG != '' 
      - name: build the image
        run: |
          docker buildx build \
          --tag multiarchbuilds/cockroach:latest --tag multiarchbuilds/cockroach:$HEAD_TAG \
          --platform linux/amd64,linux/arm64 --push .
        if: env.HEAD_TAG != '' 